container:
  image: nixos/nix
  kvm: true

environment:
  # Save some traffic by excluding the full git history
  CIRRUS_CLONE_DEPTH: 1

task:
  matrix:
    # - name: vm_test
    #   environment:
    #     channel: nixpkgs
    #     checkKVM: 1
    #   matrix:
    #     - environment:
    #         scenario: default
    #     - environment:
    #         scenario: netns

    - name: build_unstable_pkgs
      environment:
        channel: nixpkgs-unstable

  install_nix_script:
    - |
      if [[ $checkKVM && ! -e /dev/kvm ]]; then
        >&2 echo "No KVM available on VM Host."
        exit 1
      fi
    - ls -al /dev/kvm
    - whoami

    - export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix $channel)"
    - nix-env --quiet -iA cachix -f https://cachix.org/api/v1/install
    - cachix use nix-bitcoin
    - echo "$NIX_PATH ($(nix eval --raw nixpkgs.lib.version))"

  build_script:
    - printenv
