container:
  image: alpine:latest
  # kvm: true

task:
  check_script:
    - echo "hello"
    - printenv
    - whoami
    - uname -a
    - |
      fn() {
        echo myfn $1
      }
    - fn hello
    - fn world
    - exit 0
    - echo wew
