container:
  image: nixos/nix

environment:
  # Save some traffic by excluding the full git history
  CIRRUS_CLONE_DEPTH: 1

task:
  matrix:
    # - name: vm_test
    #   # container:
    #   #   kvm: true
    #   environment:
    #     nixpkgs: nixpkgs
    #   matrix:
    #     - environment:
    #         scenario: default
    #     # - environment:
    #     #     scenario: netns

    - name: build_unstable_pkgs
      environment:
        nixpkgs: nixpkgs-unstable

  build_script:
    - export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix $nixpkgs)"
    - nix run -f '<nixpkgs>' bash cachix -c ./ci/build.sh
